name: RedstoneSRV
description: sla
version: _alfa_1.1.6.12-(claim system)
main: me.skwead.RedstoneSRV
commands:
  claim:
    description: Cria uma região.
    usage: /claim <raio>
  unclaim:
    description: Elimina uma região.
    usage: /unclaim